# Generated by Django 5.0 on 2024-02-11 15:57

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=220, null=True),
        ),
    ]
