# Generated by Django 5.0 on 2024-02-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='country',
        ),
    ]
