# Generated by Django 5.0 on 2024-02-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_cartitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(blank=True, choices=[('submit for processing', 'Submit for processing'), ('processing', 'Processing'), ('ready', 'Ready for Checkout')], default='submit', max_length=250, null=True),
        ),
    ]
