# Generated by Django 5.0 on 2024-02-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_alter_cartitem_status_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='country',
            field=models.CharField(blank=True, max_length=153, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='seller',
            field=models.CharField(blank=True, max_length=153, null=True),
        ),
    ]
