# Generated by Django 5.0 on 2024-02-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_rename_phone_number_inquiry_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='status',
        ),
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
