# Generated by Django 5.0 on 2024-02-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_seller',
        ),
        migrations.AddField(
            model_name='account',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('Seller', 'Seller'), ('Buyer', 'Buyer')], max_length=220, null=True),
        ),
    ]
