# Generated by Django 5.0 on 2024-02-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Confirmed Order', 'Confirmed Order'), ('Processing Order', 'Processing Order'), ('Quality Check', 'Quality Check'), ('Product Dispatched', 'Product Dispatched'), ('Product Delivered', 'Product Delivered')], default='Confirmed Order', max_length=110),
        ),
    ]
